# External gems
# See http://ixti.net/software/2013/01/28/using-jekyll-plugins-on-github-pages.html for making `jekyll archives` work.
gems:
  - jekyll-sitemap
  - jekyll-asciidoc

exclude:
  - "/vendor/"

# Site settings
title: Team Mountain Bike St Aunes
subtitle: Le site officiel du TMBSA, club de VTT et route de Saint Aunes.
email: tmbsaintaunes@gmail.com
name: TMBSA
description: >
  Le site officiel du TMBSA, club de VTT et route de Saint Aunes.
# Base URL of site (i.e. /blog). It should always start with a slash,
# and never end with a slash. Set it to a blank value if hosting at the
# root of your server.
baseurl: "/tmbsa.github.io/" # the subpath of your site, e.g. /blog/

# Debug Localhost page
url: "http://127.0.0.1:4000" # the base hostname & protocol for your site

# Github page
url: "https://tgirard12.github.io" # the base hostname & protocol for your site

cover: "/assets/header_image.jpg"
logo: "/assets/logo.png"
ne_jetez_plus: "/assets/ne_jetez_plus.png"

# Build settings
markdown: kramdown
#paginate: 5
#paginate_path: "/page:num/"
inter_post_navigation: false
highlightjs_theme: "monokai_sublime"

# Social icons and sharing options
#
# Social settings are used in two places:
# * In the footer, as links to your personal profiles
# * After each blog post for sharing widgets
#
# Example:
#
# social:
#   - name: Twitter                         # Name of the service
#     icon: twitter                         # Font Awesome icon to use (minus fa- prefix)
#     username: "@TheBenCentra"             # (User) Name to display in the footer link
#     url: https://twitter.com/TheBenCentra # URL of your profile (leave blank to not display in footer)
#     desc: Follow me on Twitter            # Description to display as link title, etc
#     share: true                           # Include in the "Share" section of posts
social:

  - name: Facebook
    icon: facebook
    username: Tmb-Saint-Aunes
    url: https://www.facebook.com/TMBSaintAunes/
    desc: Le Facebook du TMB Saint Aunes
    share: true

  - name: Twitter
    icon: twitter
    username: Tmb-Saint-Aunes
    url:
    desc:
    share: true

  - name: Strava
    icon: bicycle
    username: Strava Tmb-Saint-Aunes
    url: https://www.strava.com/clubs/Tmb-Saint-Aunes
    desc:
    share: false

# Social sharing protocols
# These are for automatically generating sharing metadata for FB and Twitter
# OS Protocol is for sharing the source of your site, if you're interested. For more, see osprotocol.com
protocols:
    fb_image: "/assets/logo.png"
    fb_image_width: 612
    fb_image_height: 605
    fb_image_type: "image/png"

    twitter_image: "/assets/logo.png"

    os_repo: "https://github.com/bencentra/centrarium.com"
    os_rcs_type: "git"
    os_src: "git@github.com:bencentra/centrarium.com.git"
